# Generated by Django 3.2.16 on 2023-06-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Задаёт текст комментария'),
        ),
    ]
