# Generated by Django 3.2.16 on 2023-06-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='img/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
